### ISSUE TITLE
Shownotes ostrukturerad v15

### ISSUE THREAD

**Issue by mjidhage** [mjidhage/sakerhetspodcasten#28]

**Comment by blaufish** [comment]
Shout outs

Göteborg Hackathon http://www.youtube.com/watch?v=QP5kgJg2lgI
OWASP Privacy by Design http://www.eventbrite.com/e/privacy-by-design-tickets-11189308523
Egna Projekt

Bergvärmeprotokollen Rikard uteslutit: http://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus & http://en.wikipedia.org/wiki/I%C2%B2C
Rikard Raspery pi http://www.raspberrypi.org, Tid från GPS http://www.lammertbies.nl/comm/info/GPS-time.html
Jidhages Yagi antenn http://en.wikipedia.org/wiki/Yagi-Uda_antenna
Mattias misstänkta protokoll POCSAG http://en.wikipedia.org/wiki/POCSAG
Mattias AFSK http://en.wikipedia.org/wiki/Frequency-shift_keying#Audio_FSK
Peter Super 16 optik http://en.wikipedia.org/wiki/16_mm_film#Super_16_mm & http://en.wikipedia.org/wiki/C-mount
Peter Anamorphic http://www.vid-atlantic.com/anamorphic/
Diverse/nyheter

5 åring hackar xbox med en massa spejs http://www.theregister.co.uk/2014/04/04/five_year_olds_xbox_live_password_hack/
Cryptolocker C&C hackat http://tghc.co/cryptolocker-you-little-shit/
Brian Krebs The Movie http://krebsonsecurity.com/2014/03/sony-pictures-plans-movie-about-yours-truly/
Simon Singh http://en.wikipedia.org/wiki/Simon_Singh
Kodboken http://www.bokus.com/bok/9789113007083/kodboken/ &  http://en.wikipedia.org/wiki/The_Code_Book
Libel Tourism http://en.wikipedia.org/wiki/Libel_tourism
McAfee artikeln om… öh… anställa hackers… kanske? Tyvärr är denna underbara nätsnackis numera bakom paywall, så det är än mer svårt att avgöra vad deras förvirrade CSO ville ha sagt http://www.securitymagazine.com/articles/85263-why-not-to-hire-an-ethical-hacker
Robert L. Mitchell lyckades bli arg på https-skyddad mail, och internet suckade! :)  http://blogs.computerworld.com/privacy/23698/google-customers-you-will-use-https
HSTS för Internet Explorer 12 http://www.cso.com.au/article/542244/microsoft_confirms_http_strict_transport_security_ie_12/
Strict Transport Security http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security
Windows XP end of life http://windows.microsoft.com/en-us/windows/end-support-help
Windows XP på bankomaten http://www.sweclockers.com/forum/22-microsoft-windows/1085999-windows-xp-i-bankomaten/
Flappy birds på iZettle Artikel https://www.mwrinfosecurity.com/media/press-releases/mobile-point-of-sale-devices-could-leave-millions-worldwide-open-to-attack/
Flappy birds på iZettle Video http://vimeo.com/89924160
USB attacker över RDP https://www.nccgroup.com/media/481258/usb_physical_access_andy_davis_ncc_group_slides.pdf
Tugg & nonsens

Gömma bilder i ljud (spektrogram) http://lifehacker.com/5807289/how-to-hide-secret-messages-and-codes-in-audio-files
Gömma bilder i ljud, exempel http://twistedsifter.com/2013/01/hidden-images-embedded-into-songs-spectrographs/
Bilder till ascii http://picascii.com/
Microsoft support scam http://www.microsoft.com/security/online-privacy/avoid-phone-scams.aspx
John ”Badsalt” McAfee: http://www.youtube.com/user/officialjohnmcafee & http://www.whoismcafee.com/
Schneier https://www.schneier.com/
Schneier – Liars and outliars https://www.schneier.com/book-lo.html
Schneier Applied Cryptography https://www.schneier.com/book-applied.html
Länkar för att ställa frågor!

Ask http://ask.fm/sakerhetspodcasten
FB https://www.facebook.com/sakerhetspodcasten
Twitter https://twitter.com/sakpodcasten

**Comment by Kadawasalif** [comment]
Hello
